replicaCount: 1

image:
  repository: hashicorp/http-echo
  tag: "1.0.0"

text: "hello from http-echo"

service:
  port: 80
  targetPort: 5678

ingress:
  enabled: true
  className: nginx
  host: http-echo.local
  path: /
